### ISSUE TITLE
TemplateDoesNotExist: mail_body.txt

### ISSUE THREAD

**Issue by xuliang2019** [LeoneBacciu/django-email-verification#12]
Hello, I have included the `mail_body.txt` under the templates folder, but the console always throws an TemplateDoesNotExist exception. The details are below:

`Traceback (most recent call last):
  File "/home/liang/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/liang/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/liang/PycharmProjects/hire_beat_react_django/env/lib/python3.7/site-packages/django_email_verification/Confirm.py", line 65, in sendConfirm_thread
    text = render_to_string(mail_plain, {'link': link})
  File "/home/liang/PycharmProjects/hire_beat_react_django/env/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/liang/PycharmProjects/hire_beat_react_django/env/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: mail_body.txt
`

Besides, the attachment is my working tree. I called the `sendConfirm` function in the `api.api.py` file. Could someone help me out? Thanks!
![Screenshot from 2020-08-07 17-22-21](https://user-images.githubusercontent.com/46463507/89697890-26455b00-d8d3-11ea-955d-54750de7129f.png)

**Comment by LeoneBacciu** [comment]
Check out the issue #10 , probably you have not correctly set up the templates folders in the settings.py file.

**Comment by LeoneBacciu** [comment]
Have you solved? Can I close this issue?

**Comment by xuliang2019** [comment]
Hello Leone, I implemented the function with another method. Your idea might help to solve this problem.  You can close this issue.Thanks
