### ISSUE TITLE
How to set the path of EMAIL_MAIL_HTML and EMAIL_PAGE_TEMPLATE ?

### ISSUE THREAD

**Issue by doutv** [LeoneBacciu/django-email-verification#9]
Your project is nice~  
I encounter a problem when I call function `sendConfirm` in `views.py`, I try to set `EMAIL_MAIL_HTML='mail_body.html' or '/qa/static/mail_body.html'` in `settings.py` but all fail.
```python
EMAIL_MAIL_HTML /qa/static/mail_body.html
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Jason\miniconda3\envs\ciwk\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Jason\miniconda3\envs\ciwk\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Jason\miniconda3\envs\ciwk\lib\site-packages\django_email_verification\Confirm.py", line 74, in sendConfirm_thread
    html = render_to_string(mail_html, {'link': link})
  File "C:\Users\Jason\miniconda3\envs\ciwk\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Jason\miniconda3\envs\ciwk\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /qa/static/mail_body.html
```
My project structure is as below and I put `mail_body.html` and `confirm_template.html` under `/qa/static/`
```
├─ciwkbe
│  └─__pycache__
└─qa
    ├─migrations
    │  └─__pycache__
    ├─static
    └─__pycache__
```

**Comment by LeoneBacciu** [comment]
You have to setup at least one "templates" directory as shown in https://docs.djangoproject.com/en/3.0/topics/templates/#configuration. Than you insert the path relative to your "templates" directory in the EMAIL_MAIL_HTML field.

**Comment by doutv** [comment]
Thanks for your reply. Since my project uses frontend and backend separation, I have decided to implement email verification by myself.
